### ISSUE TITLE
Interface for assignments

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/VREPaaS#92]
```[tasklist]
### Tasks
- [ ] https://github.com/QCDIS/VREPaaS/issues/93
- [ ] https://github.com/QCDIS/VREPaaS/issues/94
- [ ] https://github.com/QCDIS/VREPaaS/issues/95
- [ ] https://github.com/QCDIS/VREPaaS/issues/96
```

**Comment by latifedag** [comment]
can u take a look at all? @gpelouze
