### ISSUE TITLE
Assignment Management

### ISSUE THREAD

**Issue by latifedag** [QCDIS/VREPaaS#97]
```[tasklist]
### Tasks
- [ ] https://github.com/QCDIS/VREPaaS/issues/98
- [ ] https://github.com/QCDIS/VREPaaS/issues/99
- [ ] https://github.com/QCDIS/VREPaaS/issues/100
- [ ] https://github.com/QCDIS/VREPaaS/issues/101
- [ ] https://github.com/QCDIS/VREPaaS/issues/132
```

**Comment by latifedag** [comment]
Add or modify new assignments(tutors only)
 Enroll in assignments(students/tutor)
